### ISSUE TITLE
Link liboqs statically

### ISSUE THREAD

**Issue by stv0g** [open-quantum-safe/liboqs-go#25]
Does liboqs-go support static linking against liboqs?

I would like to build a statically linked Go executable without external depdendencies..

**Comment by stv0g** [comment]
Here is an example as used by go-rosenpass: https://github.com/stv0g/go-rosenpass/commit/fb93e83dbddd92b60da5feef68f5d0230d4a3684

**Comment by vsoftco** [comment]
@stv0g Thanks, I'll look into it this week

**Comment by vsoftco** [comment]
@stv0g The only way to link statically is a bit hacky. In [`oqs.go`](https://github.com/open-quantum-safe/liboqs-go/blob/main/oqs/oqs.go), immediately after the line https://github.com/open-quantum-safe/liboqs-go/blob/e3e87437a36ce5f154ad38f81b11278187c896a5/oqs/oqs.go#L6, add the line `#cgo LDFLAGS: /usr/local/liboqs.a` (of course with the path corresponding to your location of liboqs.a`). Next, comment the last line starting with `Libs:` of [`.config/liboqs.pc`](https://github.com/open-quantum-safe/liboqs-go/blob/main/.config/liboqs.pc), i.e., https://github.com/open-quantum-safe/liboqs-go/blob/e3e87437a36ce5f154ad38f81b11278187c896a5/.config/liboqs.pc#L9. Then do a `go clean -cache` to force pkg-config to use the updated `liboqs.pc`.

As far as I know, there's no elegant way of statically linking by only modifying the `liboqs.pc` file.

**Comment by vsoftco** [comment]
Fixed by #37
