### ISSUE TITLE
Go Version outside of support window

### ISSUE THREAD

**Issue by MichaelMcAleer** [open-quantum-safe/liboqs-go#32]
Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. 

The latest version of Go is 1.21.4. The version of Go used by liboqs-go is 1.15. Go 1.15 was released over 3 years ago on the 11th August 2020, and support ended over 2 years ago on the 16th August 2021.

A number of CVEs have been detected in Go versions 1.15 to 1.20. Please consider upgrading Go to latest version 1.21.4 to make use of security fixes. 

https://go.dev/doc/devel/release#go1.21.minor

**Comment by vsoftco** [comment]
Done, see https://github.com/open-quantum-safe/liboqs-go/commit/797f72541a53867d3e77e1fa6ec8aaae3b82a855
