### ISSUE TITLE
Does the GenerateKeyPair() function always flush secret key?

### ISSUE THREAD

**Issue by JackMingQiu** [open-quantum-safe/liboqs-go#45]
After I created a object of signer and generated a pair of pk/sk using GenerateKeyPair(), I exported the sk and reused to created a new signer. Then I want to generate a new pk from the second signer by using GenerateKeyPair(), but I found that the function generates a new pair of sk/pk, instead of using the reused sk. So is this a bug?
here is the test code:
```
        sigName := "Dilithium2"
	signer := oqs.Signature{}
	defer signer.Clean() // clean up even in case of panic

	if err := signer.Init(sigName, nil); err != nil {
		log.Fatal(err)
	}

	fmt.Println("\nSignature details:")
	fmt.Println(signer.Details())

	msg := []byte("This is the message to sign")
	pubKey, err := signer.GenerateKeyPair()
	if err != nil {
		log.Fatal(err)
	}
	sk := signer.ExportSecretKey()

        signer2 := oqs.Signature{}

        //reuse the sk
	if err := signer2.Init(sigName, sk); err != nil {
		log.Fatal(err)
	}
	fmt.Println("is same sk", bytes.Equal(sk, signer2.ExportSecretKey())) //the result is true

	pk, err := signer2.GenerateKeyPair()
	if err != nil {
		log.Fatal(err)
	}

        fmt.Println("is same sk", bytes.Equal(sk, signer2.ExportSecretKey())) //the result is false
```

If I sign a message directly after initializing signer2, then it can be verified with same pk. However, I can't export the pk from signer2. Because I found no function can provide this functionality.

**Comment by SWilson4** [comment]
This is the intended behaviour: `GenerateKeyPair` generates a fresh key pair at each invocation. There is no functionality in liboqs (hence also not in liboqs-go) to derive a public key from its corresponding private key.
