### ISSUE TITLE
Port travisCI to CircleCI

### ISSUE THREAD

**Issue by vsoftco** [open-quantum-safe/liboqs-go#7]

**Comment by baentsch** [comment]
Just checking out .travis.yml: Is go 1.11 _required or should things also work with 1.14 (which we already have in our standard build docker image)?

**Comment by baentsch** [comment]
Answering my own question: Looks like it: Local CCI execution worked OK with go 1.14. 
Actual CCI will probably only happen once #8 is merged and the server can find the config file....

**Comment by vsoftco** [comment]
Thanks! Should work with higher Go versions, 1.11 is the minimum required

**Comment by vsoftco** [comment]
Works like a charm on Ubuntu, almost on macOS (couldn't yet figured out how to install GoLang...) Thanks!!

**Comment by baentsch** [comment]
Glad to hear that, Thanks. Now that the jobs are starting on CCI, you can actually re-run them with SSH access such as to log in to the running test machine and "look around" there, e.g., to check out how to install golang: 
![grafik](https://user-images.githubusercontent.com/57787676/104755973-70244e00-575b-11eb-9b52-0a05c1e31146.png)
Let me know if I should take a look (though I'm neither a Mac, nor golang "expert").

**Comment by vsoftco** [comment]
All good, thanks, closing. Will replicate the config for liboqs-cpp as well.
